# environment setup
language: swift
osx_image: xcode14
# caching of dependencies
cache:
  bundler: true
  directories:
    - Carthage
# run jobs on changes to master only
branches:
  only:
    - main
# prepare dependency managers
before_install:
  - brew update
  - brew outdated carthage || brew upgrade carthage
  - gem install bundler -v "$(grep -A 1 "BUNDLED WITH" Gemfile.lock | tail -n 1)"
# install dependencies
install:
  - travis_wait carthage bootstrap --platform iOS --cache-builds
  - bundle install
# jobs and stages to run
jobs:
  include:
    - stage: "Test"
      name: "Unit tests"
      script:
        - bundle exec fastlane unit_test
