workflows:
  ios-project-debug: # workflow ID
    name: iOS debug # workflow name
    environment:
      xcode: latest
      cocoapods: default
      vars:
          BUNDLE_ID: "com.aditya.dicoding.TriangleApp" # replace with your app bundle
          XCODE_PROJECT: "TriangleApp.xcodeproj" # Isikan nama project Anda.
          XCODE_SCHEME: "TriangleApp" # Isikan nama scheme project Anda.
    scripts:
      - name: Run tests
        script: |
          #!/bin/sh
          set -ex
          xcode-project run-tests \
            --project "$XCODE_PROJECT" \
            --scheme "$XCODE_SCHEME" \
            --device "iPhone 11" \
            --test-xcargs "CODE_SIGNING_ALLOWED=NO" "CODE_SIGNING_REQUIRED=NO" "CODE_SIGNING_ALLOWED=NO"
        test_report: build/ios/test/*.xml
      - name: Build debug app
        script: |
          xcodebuild build \
          -project "$XCODE_PROJECT" \
          -scheme "$XCODE_SCHEME" \
          CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO CODE_SIGNING_ALLOWED=NO
    artifacts:
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
    publishing:
      email:
        recipients:
          - nuradityo@gmail.com
        notify:
          success: true
          failure: true
